### ISSUE TITLE
Problem with deploy in Binder

### ISSUE THREAD

**Issue by jrhumberto** [ipeaGIT/intro_access_book#18]
Problem with deploy in Binder.
Message: 

_Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerw2gro626'...
HEAD is now at 6e408a5 closes #15
Using DockerBuildPack builder
Step 1/9 : FROM ipea/intro_access_book:latest
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit_

**Comment by dhersz** [comment]
Hi @jrhumberto, thanks for opening this issue.

Unfortunately there's not much we can do from our side. The referred link says: _"Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours"_. I'd guess that the sudden visitors spike caused this issue.

Since we don't plan to upgrade our DockerHub account anytime soon, I suggest waiting a few hours before trying to use the binder or cloning the repo to play with the code locally.

I'll add a note at the binder passage in the book to warn about this error and will close the issue afterwards. Cheers!

PS: It seems that the binder is already working again.
